language: python
os: linux

python:
    - "3.6"

install:
    - pip install -r requirements.txt

script:
    bash -c "for midi in examples/*.mid; do python -O process_music/process_music.py ${midi}; done"